package com.example.hhplus_ecommerce.presentation.common;

public enum ErrorCode {
    INVALID_PARAMETER_TYPE,
    MISSING_PATH_VARIABLE,
    INVALID_ARGUMENT,
    INVALID_REQUEST_BODY,
    MISSING_REQUEST_PARAMETER,
    METHOD_NOT_ALLOWED,
    UNSUPPORTED_MEDIA_TYPE,
    BINDING_ERROR,
    CONSTRAINT_VIOLATION,

    PRODUCT_NOT_FOUND,
    USER_NOT_FOUND,
    ORDER_NOT_FOUND,
    CART_ITEM_NOT_FOUND,
    COUPON_NOT_FOUND,

    INSUFFICIENT_STOCK,
    INSUFFICIENT_POINT,
    INVALID_POINT_AMOUNT,
    INVALID_CHARGE_AMOUNT,
    INVALID_QUANTITY,
    INVALID_ORDER_STATUS,

    COUPON_EXPIRED,
    COUPON_SOLD_OUT,
    COUPON_ALREADY_USED,

    INTERNAL_SERVER_ERROR
}
