package com.example.hhplus_ecommerce.presentation.common;

public enum ErrorCode {
    INVALID_PARAMETER_TYPE,
    MISSING_PATH_VARIABLE,
    INVALID_ARGUMENT,
    INVALID_REQUEST_BODY,
    MISSING_REQUEST_PARAMETER,
    METHOD_NOT_ALLOWED,
    UNSUPPORTED_MEDIA_TYPE,
    BINDING_ERROR,
    CONSTRAINT_VIOLATION,

    PRODUCT_NOT_FOUND,
    USER_NOT_FOUND,
    ORDER_NOT_FOUND,
    INSUFFICIENT_STOCK,
    INSUFFICIENT_POINT,

    INTERNAL_SERVER_ERROR
}
